#!/usr/bin/python

import os
import requests
import sys
import datetime

#url = 'https://akqa.egnyte.com/dd/OWC0RH1Q9Z/testDN_'
#directory = '/home/ybusel'
url = raw_input("Enter the URL : ")
directory = raw_input("Where would you want to save the file ? ") 	

localFilename = url.split('/')[-1]
with open(directory + '/' + localFilename, 'wb') as f:

    r = requests.get(url, stream=True)
    total_length = r.headers.get('content-length')
    dl = 0
    start = datetime.datetime.now()
    if total_length is None: # no content length header
     f.write(r.content)
    else:
    	for chunk in r.iter_content(chunk_size=1024):
		if chunk:

        		dl += len(chunk)
        		f.write(chunk)

    end = datetime.datetime.now()
    elapsed_time = end - start
    fsize_in_kb = (dl / 1000)	
    downspeed = (fsize_in_kb / elapsed_time.seconds)
#        done = int(50 * dl/total_length)
       		#	print "Downloaded %02d MB file. " % int(dl) 
    print  "Download speed is %d kbps" % (downspeed)
    print  "Download time is %d secs" % (elapsed_time.seconds) 

os.remove(directory + '/' + localFilename)

