#!/usr/bin/python

import pycurl
import sys
import os
import datetime

size = os.stat('/tmp/testU').st_size
c = pycurl.Curl()
file = open('/tmp/testU')
url = 'ftp://ftp-akqa.egnyte.com/Private/egnyte.nasync/SJC_Upload/'
filename = 'testU'

c.setopt(pycurl.URL, url+filename)
c.setopt(pycurl.USERPWD, 'egnyte.nasync$akqa:2*2equal4')
c.setopt(pycurl.FTP_USE_EPSV,0)
c.setopt(pycurl.FTP_SSL,1)
c.setopt(pycurl.VERBOSE, 1)
c.setopt(pycurl.INFILE, file)
start = datetime.datetime.now()
c.setopt(pycurl.UPLOAD, 1)
c.perform()

end = datetime.datetime.now()
elapsed_time = end - start
fsize_in_kb = (size / 1000)
upspeed = (fsize_in_kb / elapsed_time.seconds)

c.setopt(pycurl.CUSTOMREQUEST, "DELETE")
c.perform()

c.close()

print "Upload speed is %d kbps" % (upspeed)
print "Upload time is %d secs" % (elapsed_time.seconds)
